# -*- coding: utf-8 -*-
"""
External validation of frequency prediction models on literature bridges

This repository-ready version uses paths relative to the repository root,
so no user-specific absolute Windows paths are required.

This code:
- Loads SVR, Random Forest, XGBoost, and MLP models from existing .pkl files.
- Retrains only the LightGBM model.
- Produces ML predictions for f1 and f2.
- Applies linear and symbolic closed-form equations for f1 and f2.
- Calculates performance only on the literature dataset.
- Does not include training-data performance in the report.
- Creates the heatmap using absolute error, i.e., error in Hz.
- Excludes bridges without f2 values from the f2 performance calculation.
- Produces a Word report, Excel file, and figures.
"""

import os
import warnings
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

from sklearn.model_selection import KFold, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import TransformedTargetRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from lightgbm import LGBMRegressor

from docx import Document
from docx.shared import Inches


warnings.filterwarnings("ignore")


# =======================================================
# 1) REPOSITORY-RELATIVE FILE PATHS
# =======================================================
#
# Expected repository structure:
#
# repository/
# ├── data/
# │   ├── All_Results_frekans.xlsx
# │   └── bridge_model_combinations_literature.xlsx
# ├── models/
# │   ├── Best_Freq1_Hz_SVR_RBF.pkl
# │   ├── Best_Freq1_Hz_Random_Forest.pkl
# │   ├── Best_Freq1_Hz_XGBoost.pkl
# │   ├── Best_Freq1_Hz_MLP.pkl
# │   ├── Best_Freq2_Hz_SVR_RBF.pkl
# │   ├── Best_Freq2_Hz_Random_Forest.pkl
# │   ├── Best_Freq2_Hz_XGBoost.pkl
# │   └── Best_Freq2_Hz_MLP.pkl
# ├── outputs/
# └── code/                         # optional
#     └── 03_external_validation.py
#
# The script also works if it is stored directly in the repository root.

SCRIPT_DIR = Path(__file__).resolve().parent

if SCRIPT_DIR.name.lower() in {"code", "scripts", "src"}:
    PROJECT_ROOT = SCRIPT_DIR.parent
else:
    PROJECT_ROOT = SCRIPT_DIR

training_data_path = PROJECT_ROOT / "data" / "All_Results_frekans.xlsx"
literature_data_path = (
    PROJECT_ROOT / "data" / "bridge_model_combinations_literature.xlsx"
)

output_dir = PROJECT_ROOT / "outputs" / "external_validation"
output_dir.mkdir(parents=True, exist_ok=True)

# The four pre-trained ML models are generated by 01_train_ml_models.py.
pkl_dir = PROJECT_ROOT / "models"
pkl_dir.mkdir(parents=True, exist_ok=True)

if not training_data_path.exists():
    raise FileNotFoundError(
        f"Training dataset not found:\n{training_data_path}\n\n"
        "Place 'All_Results_frekans.xlsx' in the data/ folder."
    )

if not literature_data_path.exists():
    raise FileNotFoundError(
        f"Literature dataset not found:\n{literature_data_path}\n\n"
        "Place 'bridge_model_combinations_literature.xlsx' in the data/ folder."
    )


# =======================================================
# 2) SÜTUNLAR
# =======================================================

feature_cols = [
    "Kemer Açıklığı (m)",
    "Uzunluk (m)",
    "Genişlik (m)",
    "Yükseklik (m)",
    "E (MPa)",
    "d (kN/m3)"
]

target_cols = ["Freq1 (Hz)", "Freq2 (Hz)"]

cv = KFold(n_splits=5, shuffle=True, random_state=42)


# =======================================================
# 3) YARDIMCI FONKSİYONLAR
# =======================================================

def clean_numeric_columns(df, cols):
    for col in cols:
        if col in df.columns:
            df[col] = (
                df[col]
                .astype(str)
                .str.replace(",", ".", regex=False)
                .str.replace(" ", "", regex=False)
                .str.strip()
            )
            df[col] = pd.to_numeric(df[col], errors="coerce")
    return df


def calculate_metrics(y_true, y_pred):
    y_true = pd.Series(y_true)
    y_pred = pd.Series(y_pred)

    valid = pd.notna(y_true) & pd.notna(y_pred)

    y_true = np.array(y_true[valid], dtype=float)
    y_pred = np.array(y_pred[valid], dtype=float)

    if len(y_true) == 0:
        return np.nan, np.nan, np.nan, np.nan

    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))

    if len(y_true) > 1:
        r2 = r2_score(y_true, y_pred)
    else:
        r2 = np.nan

    nonzero = y_true != 0
    if np.any(nonzero):
        mape = np.mean(np.abs((y_true[nonzero] - y_pred[nonzero]) / y_true[nonzero])) * 100
    else:
        mape = np.nan

    return mae, rmse, r2, mape


def add_dataframe_table_to_doc(doc, df, title=None, decimals=4):
    if title is not None:
        doc.add_heading(title, level=2)

    table = doc.add_table(rows=1, cols=len(df.columns))
    table.style = "Table Grid"

    hdr = table.rows[0].cells
    for j, col in enumerate(df.columns):
        hdr[j].text = str(col)

    for _, row in df.iterrows():
        cells = table.add_row().cells
        for j, col in enumerate(df.columns):
            val = row[col]

            if isinstance(val, float) or isinstance(val, np.floating):
                if pd.isna(val):
                    cells[j].text = ""
                else:
                    cells[j].text = f"{val:.{decimals}f}"
            else:
                if pd.isna(val):
                    cells[j].text = ""
                else:
                    cells[j].text = str(val)

    doc.add_paragraph("")


def safe_filename(text):
    text = str(text)

    replacements = {
        " ": "_",
        "(": "",
        ")": "",
        "/": "_",
        "\\": "_",
        "²": "2",
        "³": "3",
        "ı": "i",
        "ğ": "g",
        "ü": "u",
        "ş": "s",
        "ö": "o",
        "ç": "c",
        "İ": "I",
        "Ğ": "G",
        "Ü": "U",
        "Ş": "S",
        "Ö": "O",
        "Ç": "C"
    }

    for k, v in replacements.items():
        text = text.replace(k, v)

    return text


# =======================================================
# 4) FORMÜLLER
# =======================================================

def formula_f1_linear(K, L, W, H, E, rho):
    return 27.147 - 0.619*K - 0.302*L + 3.158*W - 1.019*H + 0.002*E - 0.4*rho


def formula_f1_symbolic(K, L, W, H, E, rho):
    with np.errstate(divide="ignore", invalid="ignore", over="ignore"):
        base = (W**1.5087 * E) / (H * rho)
        exponent = (K * L) ** (-0.1149)
        return base ** exponent


def formula_f2_linear(K, L, W, H, E, rho):
    return 46.402 - 1.221*K - 0.468*L + 3.307*W - 0.909*H + 0.003*E - 0.662*rho


def formula_f2_symbolic(K, L, W, H, E, rho):
    with np.errstate(divide="ignore", invalid="ignore", over="ignore"):
        return 15.549 * np.sqrt((W * E) / (K * L * rho))


# =======================================================
# 5) LIGHTGBM MODELİ
# =======================================================

def build_lightgbm_model():
    lgbm_pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("model", LGBMRegressor(
            objective="regression",
            random_state=42,
            verbose=-1
        ))
    ])

    lgbm_ttr = TransformedTargetRegressor(
        regressor=lgbm_pipe,
        func=np.log1p,
        inverse_func=np.expm1
    )

    lgbm_params = {
        "regressor__model__n_estimators": [200, 400, 600],
        "regressor__model__learning_rate": [0.03, 0.05, 0.1],
        "regressor__model__max_depth": [-1, 4, 6],
        "regressor__model__num_leaves": [15, 31, 63],
        "regressor__model__min_child_samples": [5, 10, 20]
    }

    return lgbm_ttr, lgbm_params


# =======================================================
# 6) EĞİTİM VERİSİNİ OKU
# =======================================================

df_train = pd.read_excel(training_data_path)

numeric_cols_train = feature_cols + target_cols
df_train = clean_numeric_columns(df_train, numeric_cols_train)
df_train = df_train.dropna(subset=numeric_cols_train)

print("Training data size:", df_train.shape)


# =======================================================
# 7) LİTERATÜR VERİSİNİ OKU
# =======================================================

df_lit_raw = pd.read_excel(literature_data_path)

literature_column_map = {
    "K Kemer açıklığı (m)": "Kemer Açıklığı (m)",
    "Köprü Uzunluğu L (m)": "Uzunluk (m)",
    "Köprü Genişliği W (m)": "Genişlik (m)",
    "Yükseklik H (m)": "Yükseklik (m)",
    "Elastisite E (MPa)": "E (MPa)",
    "Birim Hacim Ağırlık (kN/m³)": "d (kN/m3)",
    "Birim Hacim Ağırlık (kN/m3)": "d (kN/m3)",
    "1. Frekans (Hz)": "Freq1 (Hz)",
    "2. Frekans (Hz)": "Freq2 (Hz)",
    "Köprü": "Köprü"
}

df_lit = df_lit_raw.rename(columns=literature_column_map)

required_lit_cols = feature_cols + target_cols + ["Köprü"]
missing_cols = [c for c in required_lit_cols if c not in df_lit.columns]

if len(missing_cols) > 0:
    raise ValueError(f"Missing columns in the literature file: {missing_cols}")

df_lit = clean_numeric_columns(df_lit, feature_cols + target_cols)
df_lit = df_lit.dropna(subset=feature_cols)

print("Literature data size:", df_lit.shape)


# =======================================================
# 8) FORMÜL TAHMİNLERİ
# =======================================================

K = df_lit["Kemer Açıklığı (m)"].values
L = df_lit["Uzunluk (m)"].values
W = df_lit["Genişlik (m)"].values
H = df_lit["Yükseklik (m)"].values
E = df_lit["E (MPa)"].values
rho = df_lit["d (kN/m3)"].values

df_lit["f1_Linear_Formula"] = formula_f1_linear(K, L, W, H, E, rho)
df_lit["f1_Symbolic_Formula"] = formula_f1_symbolic(K, L, W, H, E, rho)

df_lit["f2_Linear_Formula"] = formula_f2_linear(K, L, W, H, E, rho)
df_lit["f2_Symbolic_Formula"] = formula_f2_symbolic(K, L, W, H, E, rho)


# =======================================================
# 9) MEVCUT PKL MODELLERİNİ YÜKLE
# =======================================================

pkl_files = {
    "Freq1 (Hz)": {
        "SVR RBF": "Best_Freq1_Hz_SVR_RBF.pkl",
        "Random Forest": "Best_Freq1_Hz_Random_Forest.pkl",
        "XGBoost": "Best_Freq1_Hz_XGBoost.pkl",
        "MLP": "Best_Freq1_Hz_MLP.pkl"
    },
    "Freq2 (Hz)": {
        "SVR RBF": "Best_Freq2_Hz_SVR_RBF.pkl",
        "Random Forest": "Best_Freq2_Hz_Random_Forest.pkl",
        "XGBoost": "Best_Freq2_Hz_XGBoost.pkl",
        "MLP": "Best_Freq2_Hz_MLP.pkl"
    }
}


for target in target_cols:
    X_lit = df_lit[feature_cols].values

    for model_name, pkl_name in pkl_files[target].items():

        pkl_path = os.path.join(pkl_dir, pkl_name)

        if not os.path.exists(pkl_path):
            raise FileNotFoundError(
                f"PKL file not found: {pkl_path}\n"
                f"Run 01_train_ml_models.py first and check the models/ folder."
            )

        model = joblib.load(pkl_path)

        pred = model.predict(X_lit)

        if target == "Freq1 (Hz)":
            pred_col = f"f1_{model_name}"
        else:
            pred_col = f"f2_{model_name}"

        df_lit[pred_col] = pred

        print(f"{target} - {model_name} was loaded from the pkl file and predictions were made.")


# =======================================================
# 10) SADECE LIGHTGBM EĞİT VE TAHMİN YAP
# =======================================================

for target in target_cols:

    print(f"\nTraining LightGBM for: {target}")

    X_train = df_train[feature_cols].values
    y_train = df_train[target].values
    X_lit = df_lit[feature_cols].values

    lgbm_model, lgbm_params = build_lightgbm_model()

    search = RandomizedSearchCV(
        estimator=lgbm_model,
        param_distributions=lgbm_params,
        n_iter=12,
        cv=cv,
        scoring="r2",
        n_jobs=-1,
        random_state=42,
        verbose=1
    )

    search.fit(X_train, y_train)

    best_lgbm = search.best_estimator_
    best_lgbm.fit(X_train, y_train)

    if target == "Freq1 (Hz)":
        pred_col = "f1_LightGBM"
        pkl_name = "Best_Freq1_Hz_LightGBM.pkl"
    else:
        pred_col = "f2_LightGBM"
        pkl_name = "Best_Freq2_Hz_LightGBM.pkl"

    df_lit[pred_col] = best_lgbm.predict(X_lit)

    pkl_path = os.path.join(pkl_dir, pkl_name)
    joblib.dump(best_lgbm, pkl_path)

    print(f"{target} LightGBM completed. Best parameters:")
    print(search.best_params_)
    print(f"LightGBM pkl saved: {pkl_path}")


# =======================================================
# 11) PERFORMANS HESABI
# =======================================================

literature_perf_all = []

methods_f1 = {
    "SVR RBF": "f1_SVR RBF",
    "Random Forest": "f1_Random Forest",
    "XGBoost": "f1_XGBoost",
    "LightGBM": "f1_LightGBM",
    "MLP": "f1_MLP",
    "Linear Formula": "f1_Linear_Formula",
    "Symbolic Formula": "f1_Symbolic_Formula"
}

methods_f2 = {
    "SVR RBF": "f2_SVR RBF",
    "Random Forest": "f2_Random Forest",
    "XGBoost": "f2_XGBoost",
    "LightGBM": "f2_LightGBM",
    "MLP": "f2_MLP",
    "Linear Formula": "f2_Linear_Formula",
    "Symbolic Formula": "f2_Symbolic_Formula"
}


df_lit_f1 = df_lit.dropna(subset=["Freq1 (Hz)"]).copy()
df_lit_f2 = df_lit.dropna(subset=["Freq2 (Hz)"]).copy()


for method_name, pred_col in methods_f1.items():
    mae, rmse, r2, mape = calculate_metrics(df_lit_f1["Freq1 (Hz)"], df_lit_f1[pred_col])

    method_type = "Closed-Form Equation" if "Formula" in method_name else "Machine Learning"

    literature_perf_all.append({
        "Frequency": "Freq1 (Hz)",
        "Method": method_name,
        "Type": method_type,
        "MAE (Hz)": mae,
        "RMSE (Hz)": rmse,
        "R2": r2,
        "MAPE (%)": mape,
        "Number of Bridges Used": len(df_lit_f1)
    })


for method_name, pred_col in methods_f2.items():
    mae, rmse, r2, mape = calculate_metrics(df_lit_f2["Freq2 (Hz)"], df_lit_f2[pred_col])

    method_type = "Closed-Form Equation" if "Formula" in method_name else "Machine Learning"

    literature_perf_all.append({
        "Frequency": "Freq2 (Hz)",
        "Method": method_name,
        "Type": method_type,
        "MAE (Hz)": mae,
        "RMSE (Hz)": rmse,
        "R2": r2,
        "MAPE (%)": mape,
        "Number of Bridges Used": len(df_lit_f2)
    })


literature_perf_df = pd.DataFrame(literature_perf_all)
literature_perf_df = literature_perf_df.sort_values(["Frequency", "MAE (Hz)"])


# =======================================================
# 12) HATA SÜTUNLARI
# =======================================================

for method_name, pred_col in methods_f1.items():
    df_lit[f"{pred_col}_Abs_Error_Hz"] = np.abs(df_lit["Freq1 (Hz)"] - df_lit[pred_col])
    df_lit[f"{pred_col}_Pct_Error"] = np.abs((df_lit["Freq1 (Hz)"] - df_lit[pred_col]) / df_lit["Freq1 (Hz)"]) * 100

for method_name, pred_col in methods_f2.items():
    df_lit[f"{pred_col}_Abs_Error_Hz"] = np.abs(df_lit["Freq2 (Hz)"] - df_lit[pred_col])
    df_lit[f"{pred_col}_Pct_Error"] = np.abs((df_lit["Freq2 (Hz)"] - df_lit[pred_col]) / df_lit["Freq2 (Hz)"]) * 100


# =======================================================
# 13) GRAFİK FONKSİYONLARI
# =======================================================

figure_paths = []


def plot_observed_vs_predicted(df, true_col, methods_dict, title, filename):
    fig, ax = plt.subplots(figsize=(7, 6))

    for label, pred_col in methods_dict.items():
        valid = df[[true_col, pred_col]].dropna()
        if len(valid) > 0:
            mae, rmse, r2, mape = calculate_metrics(valid[true_col], valid[pred_col])

            if pd.notna(r2):
                legend_label = f"{label} (R² = {r2:.3f})"
            else:
                legend_label = f"{label} (R² = N/A)"

            ax.scatter(valid[true_col], valid[pred_col], label=legend_label, alpha=0.75)

    valid_true = df[true_col].dropna()

    if len(valid_true) > 0:
        min_val = min(valid_true.min(), df[list(methods_dict.values())].min().min())
        max_val = max(valid_true.max(), df[list(methods_dict.values())].max().max())
        ax.plot([min_val, max_val], [min_val, max_val], linestyle="--", label="1:1 line")

    ax.set_xlabel("Observed Frequency (Hz)")
    ax.set_ylabel("Predicted Frequency (Hz)")
    ax.set_title(title)
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    path = os.path.join(output_dir, filename)
    fig.tight_layout()
    fig.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    figure_paths.append(path)
    return path

def plot_performance_bar(perf_df, target, metric, title, filename):
    data = perf_df[perf_df["Frequency"] == target].copy()
    data = data.sort_values(metric)

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.bar(data["Method"], data[metric])
    ax.set_ylabel(metric)
    ax.set_title(title)
    ax.tick_params(axis="x", rotation=45)
    ax.grid(True, axis="y", alpha=0.3)

    path = os.path.join(output_dir, filename)
    fig.tight_layout()
    fig.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    figure_paths.append(path)
    return path


def plot_absolute_error_heatmap(df, true_col, methods_dict, title, filename):
    heatmap_data = pd.DataFrame()
    heatmap_data["Bridge"] = df["Köprü"]

    for label, pred_col in methods_dict.items():
        if pred_col in df.columns:
            heatmap_data[label] = np.abs(df[true_col] - df[pred_col])

    heatmap_data = heatmap_data.dropna(subset=[c for c in heatmap_data.columns if c != "Bridge"], how="all")

    if heatmap_data.shape[0] == 0:
        return None

    bridges = heatmap_data["Bridge"].astype(str).values
    values = heatmap_data.drop(columns=["Bridge"]).values
    methods = heatmap_data.drop(columns=["Bridge"]).columns

    fig_height = max(5, 0.38 * len(bridges))
    fig, ax = plt.subplots(figsize=(11, fig_height))

    im = ax.imshow(values, aspect="auto", cmap="RdYlGn_r")

    ax.set_xticks(np.arange(len(methods)))
    ax.set_xticklabels(methods, rotation=45, ha="right", fontsize=9)

    ax.set_yticks(np.arange(len(bridges)))
    ax.set_yticklabels(bridges, fontsize=9)

    ax.set_title(title, fontsize=14)

    cbar = plt.colorbar(im, ax=ax)
    cbar.set_label("Absolute Error (Hz)")

    for i in range(values.shape[0]):
        for j in range(values.shape[1]):
            if pd.notna(values[i, j]):
                ax.text(
                    j,
                    i,
                    f"{values[i, j]:.2f}",
                    ha="center",
                    va="center",
                    fontsize=7
                )

    path = os.path.join(output_dir, filename)
    fig.tight_layout()
    fig.savefig(path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    figure_paths.append(path)
    return path


# =======================================================
# 14) GRAFİKLERİ OLUŞTUR
# =======================================================

plot_observed_vs_predicted(
    df_lit_f1,
    "Freq1 (Hz)",
    methods_f1,
    "f1: Observed vs Predicted Frequencies for Literature Bridges",
    "f1_observed_vs_predicted.png"
)

plot_observed_vs_predicted(
    df_lit_f2,
    "Freq2 (Hz)",
    methods_f2,
    "f2: Observed vs Predicted Frequencies for Literature Bridges",
    "f2_observed_vs_predicted.png"
)

plot_performance_bar(
    literature_perf_df,
    "Freq1 (Hz)",
    "MAE (Hz)",
    "Literature Dataset f1 Performance - MAE",
    "f1_mae_bar.png"
)

plot_performance_bar(
    literature_perf_df,
    "Freq2 (Hz)",
    "MAE (Hz)",
    "Literature Dataset f2 Performance - MAE",
    "f2_mae_bar.png"
)

plot_absolute_error_heatmap(
    df_lit_f1,
    "Freq1 (Hz)",
    methods_f1,
    "Bridge-Based Absolute Error Heatmap for f1",
    "f1_absolute_error_heatmap.png"
)

plot_absolute_error_heatmap(
    df_lit_f2,
    "Freq2 (Hz)",
    methods_f2,
    "Bridge-Based Absolute Error Heatmap for f2",
    "f2_absolute_error_heatmap.png"
)


# =======================================================
# 15) EXCEL ÇIKTISI
# =======================================================

excel_output_path = os.path.join(output_dir, "literature_predictions_and_performance_results.xlsx")

output_column_map = {
    "Köprü": "Bridge",
    "Kemer Açıklığı (m)": "Arch Span (m)",
    "Uzunluk (m)": "Length (m)",
    "Genişlik (m)": "Width (m)",
    "Yükseklik (m)": "Height (m)",
    "E (MPa)": "Elastic Modulus, E (MPa)",
    "d (kN/m3)": "Unit Weight (kN/m³)"
}

df_lit_output = df_lit.rename(columns=output_column_map)

with pd.ExcelWriter(excel_output_path, engine="openpyxl") as writer:
    df_lit_output.to_excel(writer, sheet_name="Literature_Predictions", index=False)
    literature_perf_df.to_excel(writer, sheet_name="Literature_Performance", index=False)

print(f"Excel output saved: {excel_output_path}")


# =======================================================
# 16) WORD RAPORU
# =======================================================

doc = Document()

doc.add_heading("Performance Evaluation of Frequency Prediction Models on Literature Bridges", level=1)

doc.add_paragraph(
    "In this report, the machine learning models and closed-form linear/symbolic regression "
    "equations developed within the thesis are evaluated through independent external validation "
    "using bridge data reported in the literature."
)

doc.add_paragraph(
    "The SVR, Random Forest, XGBoost, and MLP models were loaded from previously saved pkl files. "
    "The LightGBM model was retrained using the same training dataset and then evaluated on the "
    "literature bridges. Performance results for the training dataset are not included in this report."
)

doc.add_paragraph(
    "Since the second natural frequency was not reported for some bridges in the literature dataset, "
    "the f2 performance metrics were calculated only by considering bridges with available f2 values. "
    "These bridges were still included in the f1 evaluation."
)

doc.add_heading("Input Parameters", level=2)

doc.add_paragraph(
    "K: arch span (m), L: bridge length (m), W: bridge width (m), "
    "H: bridge height (m), E: elastic modulus (MPa), ρ: unit weight (kN/m³)."
)

doc.add_heading("Closed-Form Equations Used", level=2)

doc.add_paragraph("Linear regression equation for f1:")
doc.add_paragraph("f1 = 27.147 - 0.619K - 0.302L + 3.158W - 1.019H + 0.002E - 0.4ρ")

doc.add_paragraph("Symbolic regression equation for f1:")
doc.add_paragraph("f1 = ((W^1.5087 E) / (Hρ))^((KL)^(-0.1149))")

doc.add_paragraph("Linear regression equation for f2:")
doc.add_paragraph("f2 = 46.402 - 1.221K - 0.468L + 3.307W - 0.909H + 0.003E - 0.662ρ")

doc.add_paragraph("Symbolic regression equation for f2:")
doc.add_paragraph("f2 = 15.549 sqrt(WE / (KLρ))")


add_dataframe_table_to_doc(
    doc,
    literature_perf_df,
    title="External Validation Performance on the Literature Dataset",
    decimals=4
)

doc.add_heading("Graphical Evaluation", level=2)

for fig_path in figure_paths:
    if fig_path is not None and os.path.exists(fig_path):
        doc.add_picture(fig_path, width=Inches(6.5))
        doc.add_paragraph(os.path.basename(fig_path))


doc.add_heading("Bridge-Based Observed and Predicted Frequencies", level=2)

selected_cols = [
    "Köprü",

    "Freq1 (Hz)",
    "f1_SVR RBF",
    "f1_Random Forest",
    "f1_XGBoost",
    "f1_LightGBM",
    "f1_MLP",
    "f1_Linear_Formula",
    "f1_Symbolic_Formula",

    "Freq2 (Hz)",
    "f2_SVR RBF",
    "f2_Random Forest",
    "f2_XGBoost",
    "f2_LightGBM",
    "f2_MLP",
    "f2_Linear_Formula",
    "f2_Symbolic_Formula"
]

selected_cols = [c for c in selected_cols if c in df_lit.columns]
table_df = df_lit[selected_cols].copy()
table_df = table_df.rename(columns=output_column_map)

add_dataframe_table_to_doc(
    doc,
    table_df,
    title="Observed and Predicted Frequencies for Literature Bridges",
    decimals=3
)


doc.add_heading("Brief Evaluation", level=2)

best_f1 = literature_perf_df[literature_perf_df["Frequency"] == "Freq1 (Hz)"].sort_values("MAE (Hz)").iloc[0]
best_f2 = literature_perf_df[literature_perf_df["Frequency"] == "Freq2 (Hz)"].sort_values("MAE (Hz)").iloc[0]

doc.add_paragraph(
    f"For f1, the method with the lowest MAE on the literature dataset was "
    f"{best_f1['Method']}. Its MAE, RMSE, and MAPE values were calculated as "
    f"{best_f1['MAE (Hz)']:.3f} Hz, {best_f1['RMSE (Hz)']:.3f} Hz, and "
    f"{best_f1['MAPE (%)']:.2f}%, respectively."
)

doc.add_paragraph(
    f"For f2, the method with the lowest MAE on the literature dataset was "
    f"{best_f2['Method']}. Its MAE, RMSE, and MAPE values were calculated as "
    f"{best_f2['MAE (Hz)']:.3f} Hz, {best_f2['RMSE (Hz)']:.3f} Hz, and "
    f"{best_f2['MAPE (%)']:.2f}%, respectively."
)

doc.add_paragraph(
    "The values shown in the heatmaps are not percentage errors, but direct absolute error values. "
    "Therefore, the error values should be interpreted in Hz."
)

word_output_path = os.path.join(output_dir, "Literature_Bridges_Performance_Report.docx")
doc.save(word_output_path)

print(f"Word report saved: {word_output_path}")

print("\nALL PROCESSES COMPLETED.")